### ISSUE TITLE
生成图片大小过大，且不符合微信红包封面尺寸规格

### ISSUE THREAD

**Issue by seng1e** [all-in-aigc/aicover#4]
https://github.com/all-in-aigc/aicover/blob/abc9b7cbea85ac3fa0f8c5cec12dd59ec733081b/app/api/gen-cover/route.ts#L34C23-L34C32

我尝试下载了图片都是超过5M，并且也不符合微信红包封面957×1278像素的尺寸要求。

**Comment by david-dong828** [comment]
![image](https://github.com/all-in-aigc/aicover/assets/106771290/0290b699-69dc-46fb-a6c4-5827f7492d9e)
DALL·E 3 只能生成 1024x1024, 1024x1792 or 1792x1024 这3种格式的吧
需要加个格式转换function？

**Comment by seng1e** [comment]
感觉只是蹭蹭微信红包的话题，实际上还是一个DELL E 3 api 生成图片的套皮应用，prompt也很简单，并没有针对红包封面有什么特殊的考量。

**Comment by seng1e** [comment]
并且付费逻辑中，生成次数和下载次数分开计次，当我消耗尽余额生成了一张图时，我还需要额外再次充值才能把这张图片下载下来，有种被割的感觉.....

**Comment by david-dong828** [comment]
这倒没注意，我直接改成20次了。
但是我的页面显示有问题，显示不出图片。我把S3 permission都开了 也还这样。 而且也不能点击，不像demo里可以点击进去。
不知道是不是哪里我没做好。
请问兄弟你怎么弄的

![image](https://github.com/all-in-aigc/aicover/assets/106771290/8d1bd30f-b29e-456a-8bfb-eb2320db64cd)

**Comment by idoubi** [comment]
加了个下载压缩的功能 最新下载的图片大小低于微信红包封面要求的 500k 以内了。

代码开源的，有什么不爽你可以 pr 提修改，说话别那么难听，又不是不能用。
